DROP TABLE IF EXISTS clubes;
CREATE TABLE clubes (
id INTEGER NOT NULL UNIQUE,
nome VARCHAR(30) NOT NULL UNIQUE,
PRIMARY KEY (id)
);

DROP TABLE IF EXISTS escudos;
CREATE TABLE escudos (
id INTEGER NOT NULL UNIQUE,
id_clubes INTEGER NOT NULL UNIQUE,
url TEXT NOT NULL UNIQUE,
PRIMARY KEY(id),
FOREIGN KEY (id_clubes) REFERENCES clubes(id)
);